### ISSUE TITLE
random songs play, after linking songs from a playlist

### ISSUE THREAD

**Issue by KasperBosteels** [Koenie06/Discord.js-Music#5]
random different songs play when using youtube links from a playlist.
song being played:
```

{
  title: 'Color Song for Kids: Learn 9 Colors',
  description: 'In this fun color song with balloons we learn 9 colors. Sing-a-long and wave bye-bye to the balloons! Download over 75 Free Kids ...',
  duration: '2:05',
  views: 9580356,
  author: 'Dream English Kids',
  url: 'https://youtube.com/watch?v=z0HZNaM7gTg',
  thumbnail: 'https://i.ytimg.com/vi/z0HZNaM7gTg/hq720.jpg',
  likes: 12826,
  dislikes: 3722,
  extra: { type: 'video', playlist: null }
}

```

song requested https://www.youtube.com/watch?v=b09YiH6UW2I&list=LL&index=9
(ghost in the shell cardigans paralyzed)

**Comment by TukanDev** [comment]
hello,
This is intresting issue i never came across it myself (maybe becouse im not using playlists for now atleast) but randomly i receive
```
AudioPlayerError: aborted
    at connResetException (node:internal/errors:683:14)
    at TLSSocket.socketCloseListener (node:_http_client:407:19)
    at TLSSocket.emit (node:events:406:35)
    at node:net:662:12
    at TCP.done (node:_tls_wrap:580:7)
```
And as far as i researched this is issue with ytdl library used to fetch videos and songs from youtube but my question is:
Did you managed to experience the same error if yes then is there any quick fix for it? if you know any besides modifying the code of the module (as far as i tested not even discord-ytdl-core works and it works even worse then default one) i even tried youtube-dl but it requires harder module code modifications which can be done but at that point you can just write your own module haha

**Comment by KasperBosteels** [comment]
hello,

concerning the error,
i tried adding some options like "highWatermark", birtrate,...
to the index.js from the package.
it seemed to help a little bit, but i still get the errors from time to time.

apparently this is a new issue with node or discord.js.

Outlook voor Android<https://aka.ms/AAb9ysg> downloaden
________________________________

**Comment by TukanDev** [comment]
> 
> hello, conserving the error, i tried adding some options like "highwaterMark", birthrate,... to the index.js from the package. it seemed to help a little bit, but i still get the errors from time to time. apparently this is a new issue with node or discord.js. Outlook voor Android<https://aka.ms/AAb9ysg> downloaden
> […](#)

May i ask what is the values you passed to those args and it seems its issue with paying videos with codecs of avc (if you open stats for nerds on youtube video) and it looks there is no way to fix it [https://github.com/discordjs/voice/issues/148#issuecomment-872723948](this issue) describes it as ytdl problem, guess like i might just depoy youtube-dl into it and hopefully that will fix it, if not i might just switch to discord-player (which has issue with skipping some songs with "write EPIPE" instead of "aborted" which brings as back to codecs issue of a video. And honestly idk if there will ever be any stable fix for this issues, discord js 12 music bots worked completly fine using ytdl since i have working one so at the end its myb just best to modify this module's playing or just use discordjs/voice manually.

**Comment by KasperBosteels** [comment]
> > hello, conserving the error, i tried adding some options like "highwaterMark", birthrate,... to the index.js from the package. it seemed to help a little bit, but i still get the errors from time to time. apparently this is a new issue with node or discord.js. Outlook voor Androidhttps://aka.ms/AAb9ysg downloaden
> > […](#)
> 
> May i ask what is the values you passed to those args and it seems its issue with paying videos with codecs of avc (if you open stats for nerds on youtube video) and it looks there is no way to fix it [https://github.com/[discordjs/voice/issues/148](https://github.com/discordjs/voice/issues/148)#issuecomment-872723948](this issue) describes it as ytdl problem, guess like i might just depoy youtube-dl into it and hopefully that will fix it, if not i might just switch to discord-player (which has issue with skipping some songs with "write EPIPE" instead of "aborted" which brings as back to codecs issue of a video. And honestly idk if there will ever be any stable fix for this issues, discord js 12 music bots worked completly fine using ytdl since i have working one so at the end its myb just best to modify this module's playing or just use discordjs/voice manually.

Hello 
I changed the resource variable and added after the audioonly filter the highwatermark and 'highestquality' quality option.
This seems to have resolved the 'abort' error i was getting, but made the audio even more distorted.
```
let resource = await createAudioResource(ytdl(data.queue[0].url, { filter: 'audioonly',highWaterMark:1<<25,quality:'highestaudio'}), { 
        inputType: StreamType.Arbitrary,
        inlineVolume: true,
    });

```

"1<<25" apparently is 32Mb.

i also changed the last line in the volume export.
```
    fetchedData.resource.volume.setVolume(volume/100)


```

**Comment by TukanDev** [comment]
Thank you very much i will see how it works with those optimizations.
