### ISSUE TITLE
connection was failed to connect to vc

### ISSUE THREAD

**Issue by idk-pixel** [Koenie06/Discord.js-Music#6]
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "Connection was failed to connect to VC".] {
  code: 'ERR_UNHANDLED_REJECTION'
}
PS C:

**Comment by Koenie06** [comment]
May i see your code?

**Comment by idk-pixel** [comment]
> May i see your code?
> 

I fixed itz thanks for your so awesome package!

**Comment by Victor-Edward** [comment]
How do you fixed? I got the same problem

**Comment by Victor-Edward** [comment]
Nvm I managed to fix by removing my commands to join the voice channel.

**Comment by idk-pixel** [comment]
Sorry I was asleep. Glad to hear you've fixed the issue

**Comment by TheCodeHeist** [comment]
I got that same issue, but I fixed that by adding a particular Intent to the bot client
```js
const bot = new DiscordJS.Client({
  intents: [
    Intents.FLAGS.GUILD_VOICE_STATES,
  ]
});
```
This worked perfectly!

**Comment by CuongVnZ** [comment]
> > May i see your code?
> 
> I fixed itz thanks for your so awesome package!

So how do you fixed, I have the same now...

**Comment by TheCodeHeist** [comment]
> > > May i see your code?
> > 
> > 
> > I fixed itz thanks for your so awesome package!
> 
> So how do you fixed, I have the same now...

Have you tried my one?

**Comment by idk-pixel** [comment]
On an error, so a .catch, disconnect the jmbot from the vc :)Sent from my T-Mobile 4G LTE Device
-------- Original message --------From: Cuong Nguyen ***@***.***> Date: 10/26/21  10:25 PM  (GMT-06:00) To: "Koenie06/Discord.js-Music" ***@***.***> Cc: ":)" ***@***.***>, Author ***@***.***> Subject: Re: [Koenie06/Discord.js-Music] connection was failed to connect to vc (#6) 


May i see your code?

I fixed itz thanks for your so awesome package!

So how do you fixed, I have the same now...

**Comment by CuongVnZ** [comment]
> > > > May i see your code?
> > > 
> > > 
> > > I fixed itz thanks for your so awesome package!
> > 
> > 
> > So how do you fixed, I have the same now...
> 
> Have you tried my one?

I fixed by your method, thank you !

**Comment by TheCodeHeist** [comment]
> > > > > May i see your code?
> > > > 
> > > > 
> > > > I fixed itz thanks for your so awesome package!
> > > 
> > > 
> > > So how do you fixed, I have the same now...
> > 
> > 
> > Have you tried my one?
> 
> I fixed by your method, thank you !

Sounds great!
