### ISSUE TITLE
Is there a way to declare a default volume that isn't just blasting your ears away?

### ISSUE THREAD

**Issue by Haranmes** [Koenie06/Discord.js-Music#7]

**Comment by idk-pixel** [comment]
By going into the node_modules and changing the files somewhere in index.js

**Comment by KasperBosteels** [comment]
yes you can but as idk-pixel said you need to go into moduls/@koenie06/discord.js-music/src/index.js
 then look for the playSong function.
 then add this line under all the data. lines
 `resource.volume.setVolumeLogarithmic(1);`
(depending on yours you might need to change that 1 to something you like)

also in the function above called 'volume'
you might want to change that aswell i have there:
`fetchedData.resource.volume.setVolumeLogarithmic(volume/100)`
