### ISSUE TITLE
Playlists aren't implemented?

### ISSUE THREAD

**Issue by Rotekoppen** [Koenie06/Discord.js-Music#9]
![Skjermdump fra 2021-10-17 15-04-37](https://user-images.githubusercontent.com/33429716/137628369-e451f817-5153-43e5-99e8-0f399af2be7c.png)

**Comment by Rotekoppen** [comment]
Correcting: Unlisted playlists doesn't work

**Comment by Koenie06** [comment]
Only youtube playlists does work

**Comment by Rotekoppen** [comment]
Only some youtube playlists work, while others just add one song from the playlist

**Comment by SgtAlf** [comment]
Does someone know a workaround for this? I get the same error message.
Cant get mine to work..

**Comment by Koenie06** [comment]
There is no work around, I am working on it

**Comment by Pqoh** [comment]
this happened to me, but when i tried to put a random song, the playlist started playing...
